-- Supabase Seed SQL file generated for DSRQ Digitals Replica

INSERT INTO products (title, slug, category, description, delivery_type, image_url, status) VALUES
('Adobe Creative Cloud All Apps', 'adobe-creative-cloud', 'Design Tools', 'Full access to 20+ Adobe desktop and mobile apps including Photoshop, Illustrator, Premiere Pro, After Effects, and Lightroom with 100GB Cloud Storage.', 'team_invite', 'https://storage.googleapis.com/gpt-engineer-file-uploads/xVBFLpfsZ3URmdNUlYOxyAt3QDa2/social-images/social-1762454700805-Untitled design vvcbbb.png', 'active'),
('Canva Pro', 'canva-pro', 'Design Tools', 'Unlock 100M+ premium stock photos, videos, audio, 610k+ premium templates, Magic Resize, Background Remover, and Brand Kits.', 'team_invite', 'https://images.unsplash.com/photo-1626785774573-4b799315345d?auto=format&fit=crop&w=600&q=80', 'active'),
('ChatGPT Plus (GPT-4o & Sora)', 'chatgpt-plus', 'AI Tools', 'Access GPT-4o, DALL-E 3 image generation, Advanced Data Analysis, Custom GPTs, Web Browsing, and priority access during peak hours.', 'shared_account', 'https://images.unsplash.com/photo-1677442136019-21780efad99a?auto=format&fit=crop&w=600&q=80', 'active'),
('Midjourney v6 Alpha', 'midjourney', 'AI Tools', 'The world''s most advanced AI image generator. Create photorealistic art, architectural renders, logos, and UI graphics.', 'shared_account', 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=600&q=80', 'active'),
('CapCut Pro Desktop & Mobile', 'capcut-pro', 'Video Editing', 'Unlock Pro AI effects, auto-captions, background removal, motion tracking, 4K export, and 100GB cloud storage.', 'private_account', 'https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?auto=format&fit=crop&w=600&q=80', 'active'),
('Grammarly Premium', 'grammarly-premium', 'Writing & Productivity', 'Advanced grammar checking, tone detector, plagiarism checker, vocabulary enhancement, and AI rewrite prompts.', 'shared_account', 'https://images.unsplash.com/photo-1455390582262-044cdead277a?auto=format&fit=crop&w=600&q=80', 'active'),
('LinkedIn Premium Business', 'linkedin-premium', 'Business & Career', 'Unlimited profile browsing, 15 InMail messages per month, see who viewed your profile, LinkedIn Learning access, and AI profile builder.', 'team_invite', 'https://images.unsplash.com/photo-1611944212129-29977ae1398c?auto=format&fit=crop&w=600&q=80', 'active'),
('SEMrush Guru & Ahrefs Pack', 'semrush-ahrefs-pack', 'SEO & Marketing', 'Complete SEO toolkit for keyword research, backlink analysis, site audit, rank tracking, and competitor intelligence.', 'shared_account', 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=600&q=80', 'active');

